title: Michael Bryant Portfolio
description: <a href="resume.pdf">Resume</a> | <a href="about_me.html">About Me</a> | <a href="other_projects.html">Applied Physics and Materials Science Projects</a>
pages: About me
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
